FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD target/demo-1-0.0.1-SNAPSHOT.jar dockerdemo.jar
RUN sh -c 'touch /dockerdemo.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /dockerdemo.jar"]